//GLOBAL TYPES
export const API_FAILED = 'API_FAILED';
export const CLIENT_ERROR = 'CLIENT_ERROR'

// AUTH TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// DASHBOARD TYPES
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILED = 'GET_DASHBOARD_FAILED';

//TOP ORDER TYPES
export const GET_TOP_SELLING_ORDERS_REQUEST = 'GET_TOP_SELLING_ORDERS_REQUEST';
export const GET_TOP_SELLING_ORDERS_SUCCESS = 'GET_TOP_SELLING_ORDERS_SUCCESS';
export const GET_TOP_SELLING_ORDERS_FAILED = 'GET_TOP_SELLING_ORDERS_FAILED';

// ORDER TYPES
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
export const GET_ORDERS_DETAILS_REQUEST = 'GET_ORDERS_DETAILS_REQUEST';
export const GET_ORDERS_DETAILS_SUCCESS = 'GET_ORDERS_DETAILS_SUCCESS';
export const GET_ORDERS_DETAILS_FAILED = 'GET_ORDERS_DETAILS_FAILED';

// CATEGORY TYPES
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
export const CREATE_CATEGORIES_REQUEST = 'CREATE_CATEGORIES_REQUEST';
export const CREATE_CATEGORIES_SUCCESS = 'CREATE_CATEGORIES_SUCCESS';
export const CREATE_CATEGORIES_FAILED = 'CREATE_CATEGORIES_FAILED';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED';
export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

// FRONT SLIDES TYPES
export const GET_FRONT_SLIDES_REQUEST = 'GET_FRONT_SLIDES_REQUEST';
export const GET_FRONT_SLIDES_SUCCESS = 'GET_FRONT_SLIDES_SUCCESS';
export const GET_FRONT_SLIDES_FAILED = 'GET_FRONT_SLIDES_FAILED';

// PRODUCTS TYPES
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST';
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS';
export const CREATE_PRODUCTS_FAILED = 'CREATE_PRODUCTS_FAILED';
export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILED = 'DELETE_PRODUCTS_FAILED';
export const GET_PRODUCTS_BY_ID_REQUEST = 'GET_PRODUCTS_BY_ID_REQUEST';
export const GET_PRODUCTS_BY_ID_SUCCESS = 'GET_PRODUCTS_BY_ID_SUCCESS';
export const GET_PRODUCTS_BY_ID_FAILED = 'GET_PRODUCTS_BY_ID_FAILED';

// IMAGE UPLOAD
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_SUCCESS';
export const CLEAR_UPLOADS = 'CLEAR_UPLOADS';

// CART TYPES
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const EDIT_CART_REQUEST = 'EDIT_CART_REQUEST';
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS';
export const EDIT_CART_FAILED = 'EDIT_CART_FAILED';

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILED = 'DELETE_CART_FAILED';
export const DELETE_CART_ERROR = 'DELETE_CART_FAILED';


export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILED = 'GET_CART_FAILED';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';

export const COUPON_CODE = 'COUPON_CODE';






// COUPON TYPES
export const GET_COUPONS_REQUEST = 'GET_COUPONS_REQUEST';
export const GET_COUPONS_SUCCESS = 'GET_COUPONS_SUCCESS';
export const GET_COUPONS_FAILED = 'GET_COUPONS_FAILED';
export const CREATE_COUPONS_REQUEST = 'CREATE_COUPONS_REQUEST';
export const CREATE_COUPONS_SUCCESS = 'CREATE_COUPONS_SUCCESS';
export const CREATE_COUPONS_FAILED = 'CREATE_COUPONS_FAILED';
export const DELETE_COUPON_REQUEST = 'DELETE_COUPON_REQUEST';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAILED = 'DELETE_COUPON_FAILED';
export const GET_COUPON_BY_ID_REQUEST = 'GET_COUPON_BY_ID_REQUEST';
export const GET_COUPON_BY_ID_SUCCESS = 'GET_COUPON_BY_ID_SUCCESS';
export const GET_COUPON_BY_ID_FAILED = 'GET_COUPON_BY_ID_FAILED';
export const EDIT_COUPON_REQUEST = 'EDIT_COUPON_REQUEST';
export const EDIT_COUPON_SUCCESS = 'EDIT_COUPON_SUCCESS';
export const EDIT_COUPON_FAILED = 'EDIT_COUPON_FAILED';




