//GLOBAL TYPES
export const API_FAILED = 'API_FAILED';

// AUTH TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// DASHBOARD TYPES
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILED = 'GET_DASHBOARD_FAILED';

//TOP ORDER TYPES
export const GET_TOP_SELLING_ORDERS_REQUEST = 'GET_TOP_SELLING_ORDERS_REQUEST';
export const GET_TOP_SELLING_ORDERS_SUCCESS = 'GET_TOP_SELLING_ORDERS_SUCCESS';
export const GET_TOP_SELLING_ORDERS_FAILED = 'GET_TOP_SELLING_ORDERS_FAILED';

// ORDER TYPES
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

// CATEGORY TYPES
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

// FRONT SLIDES TYPES
export const GET_FRONT_SLIDES_REQUEST = 'GET_FRONT_SLIDES_REQUEST';
export const GET_FRONT_SLIDES_SUCCESS = 'GET_FRONT_SLIDES_SUCCESS';
export const GET_FRONT_SLIDES_FAILED = 'GET_FRONT_SLIDES_FAILED';

// PRODUCTS TYPES
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';