//GLOBAL TYPES
export const API_FAILED = 'API_FAILED';
export const CLIENT_ERROR = 'CLIENT_ERROR'

// AUTH TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// DASHBOARD TYPES
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILED = 'GET_DASHBOARD_FAILED';

//TOP ORDER TYPES
export const GET_TOP_SELLING_ORDERS_REQUEST = 'GET_TOP_SELLING_ORDERS_REQUEST';
export const GET_TOP_SELLING_ORDERS_SUCCESS = 'GET_TOP_SELLING_ORDERS_SUCCESS';
export const GET_TOP_SELLING_ORDERS_FAILED = 'GET_TOP_SELLING_ORDERS_FAILED';

// ORDER TYPES
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

// CATEGORY TYPES
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
export const CREATE_CATEGORIES_REQUEST = 'CREATE_CATEGORIES_REQUEST';
export const CREATE_CATEGORIES_SUCCESS = 'CREATE_CATEGORIES_SUCCESS';
export const CREATE_CATEGORIES_FAILED = 'CREATE_CATEGORIES_FAILED';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED';
export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

// FRONT SLIDES TYPES
export const GET_FRONT_SLIDES_REQUEST = 'GET_FRONT_SLIDES_REQUEST';
export const GET_FRONT_SLIDES_SUCCESS = 'GET_FRONT_SLIDES_SUCCESS';
export const GET_FRONT_SLIDES_FAILED = 'GET_FRONT_SLIDES_FAILED';

// PRODUCTS TYPES
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

// IMAGE UPLOAD
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_SUCCESS';
export const CLEAR_UPLOADS = 'CLEAR_UPLOADS';